# 5) შექმენით ფუნქცია, რომელიც მიიღებს ორ რიცხვს და
#  დააბრუნებს მათ გაყოფას. გამოიყენეთ "try", "except"
#  და დაამატეთ "else" რათა წარმატებულ შემთხვევაში 
# დაბეჭდოს „გაყოფა წარმატებით შესრულდა“,
#  ხოლო შეცდომისას — შესაბამისი შეტყობინება



try:
    print(10 / 5)
except:
    print("there was some error")
else:
    print("there was no errrors")